#!/usr/bin/env sh
prompt_install() {
		# This could def use community support
		if [ -x "$(command -v brew)" ]; then
			brew install $1

		elif [ -x "$(command -v apt)" ]; then
			sudo apt install $1 -y

		elif [ -x "$(command -v pkg)" ]; then
			sudo pkg install $1

		elif [ -x "$(command -v pacman)" ]; then
			sudo pacman -S $1

		else
			echo "I'm not sure what your package manager is! Please install $1 on your own and run this deploy script again. Tests for package managers are in the deploy script you just ran starting at line 13. Feel free to make a pull request at https://github.com/parth/dotfiles :)"
		fi
}

check_for_software() {
	echo "Checking to see if $1 is installed"
	if ! [ -x "$(command -v $1)" ]; then
		echo "$1 not_installed" >> ~/.changes
		prompt_install $1
	else
		echo "$1 is installed."
	    echo "$1 installed" >> ~/.changes
	fi
}

check_default_shell() { if [ -z "${SHELL##*zsh*}" ] ;then
			echo "Default shell is zsh."
			echo $SHELL >> ~/.changes
	else
	        echo $SHELL >> ~/.changes
			chsh -s $(which zsh)
	fi
}

echo "Installing zsh, vim, and tmux with their default options"

echo "Let's get started? (y/n)"
old_stty_cfg=$(stty -g)
stty raw -echo
answer=$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )
stty $old_stty_cfg
if echo "$answer" | grep -iq "^y" ;then
	echo
	echo -n  > ~/.changes
else
	echo "Quitting, nothing was changed."
	exit 0
fi

check_for_software zsh
echo
check_for_software vim
echo
check_for_software tmux
echo

check_default_shell

echo
if [ -f ~/.zshrc ]; then
	echo "zshrc exists" >> ~/.changes
    mv ~/.zshrc ~/.zshrc.old
else
    echo "zshrc not_exists" >> ~/.changes
fi
if [ -f ~/.tmux.conf ]; then
	echo "tmux.conf exists" >> ~/.changes
    mv ~/.tmux.conf ~/.tmux.conf.old
else
    echo "tmux.conf not_exists" >> ~/.changes
fi
if [ -f ~/.vimrc ]; then
	echo "vimrc exists" >> ~/.changes
    mv ~/.vimrc ~/.vimrc.old
else
    echo "vimrc not_exists" >> ~/.changes
fi
if [ -d ~/.vim/ ]; then
	echo "vim exists" >> ~/.changes
    mv ~/.vim/ ~/.vim.old/
else
    echo "vim not_exists" >> ~/.changes
fi

printf "source '$HOME/dotfiles/zsh/zshrc_manager.sh'" > ~/.zshrc
printf "so $HOME/dotfiles/vim/vimrc.vim" > ~/.vimrc
printf "source-file $HOME/dotfiles/tmux/tmux.conf" > ~/.tmux.conf

echo
cd ~ && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim -c 'PluginInstall' -c 'qa!'
cd ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
ruby extconf.rb
make

if ! [ -x "$(command -v ag)" ]; then
    echo "silver_searcher not_installed" >> ~/.changes
    if [ -x "$(command -v brew)" ]; then
        brew install the_silver_searcher
    elif [ -x "$(command -v apt)" ]; then
        sudo apt install silversearcher-ag
    fi
else
    echo "silver_searcher is installed."
    echo "silver_searcher installed" >> ~/.changes
fi

echo "Please log out and log back in for default shell to be initialized."
