#!/usr/bin/env sh

source ~/python-virtualenvs/my_venv36/bin/activate
if [ "$1" != "pypi" ]; then
    ~/python-virtualenvs/my_venv36/bin/twine upload -r testpypi dist/*
else
    ~/python-virtualenvs/my_venv36/bin/twine upload -r pypi dist/*
fi
deactivate